plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.147'
}

group = project.mod_group_id
version = project.mod_version

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

tasks.withType(AbstractArchiveTask).configureEach {
    preserveFileTimestamps = false
    reproducibleFileOrder = true
}

repositories {
    mavenCentral()
}

neoForge {
    version = project.neo_version

    runs {
        client {
            client()
        }
        server {
            server()
        }
        data {
            data()
        }
    }

    mods {
        copperworks {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'

def modProperties = [
    version: project.version,
    mod_id: project.mod_id,
    mod_name: project.mod_name,
    minecraft_version: project.minecraft_version,
    neo_version: project.neo_version
]

processResources {
    inputs.properties modProperties

    filesMatching('META-INF/neoforge.mods.toml') {
        expand modProperties
    }
}
